# ALL STRINGS IN THIS CONFIG USE MINI MESSAGE FORMAT
# https://docs.advntr.dev/minimessage/format.html
debug: false
chat:
  enabled: false

    # variables:
    # - <prefix> - requires Vault
    # - <suffix> - requires Vault
    # - <name>
    # - <message>
  format: "<name>: <message>"
  # in seconds
  cooldown: 3
  cooldownMessage: "<red>Please wait <cooldown> seconds before chatting again"

  filterWords: true
  filteredWords:
    - "shit"
    - "5hit"

  format-urls: true
  emojis-enabled: true
  addEmojisToCustomChatCompletions: true
  emojis:
    ":skull:": "☠"
    ":smile:": "☺"
    ":frown:": "☹"
    ":heart:": "<red>❤</red>"
    ":fire:": "<gold>🔥</gold>"
    ":(": "☹"
    ":)": "☺"

connectionMessages:
  modifyConnectionMessages: true

  # - <prefix> - requires Vault
  # - <suffix> - requires Vault
  # - <name>
  # - <join-number> - only available in firstJoinMessage
  firstJoinMessage: "<yellow><name> joined the game for the first time! [#<join-number>]"
  joinMessage: "<yellow><name> joined the game"
  quitMessage: "<yellow><name> left the game"

chats:
  enabled: true
  format: "<chat-name> <dark_gray>»<white> <prefix><name><white>: <message>"
  customChats:
    staff:
      name: "<gold>Staff Chat"
      permission: "potatoessentials.chats.examplestaff"
      # optional field
      command: "sc" # (needs server restart when first added)
    #vip:
    #  name: "<green>VIP Chat"
    #  permission: "potatoessentials.chats.examplevip"

serverLinks:
  enabled: false
  serverLinks:
    example:
      name: "<rainbow>Test Example Thingy"
      # requires the 'https://' at the start of the string
      url: "https://mcdragonmasters.com/PotatoEssentials"

serverList:
  motdEnabled: false
  motd:
    - "<rainbow>Example Line 1"
    - "<rainbow>Example Line 2"
  hoverInfoEnabled: false
  # gradients don't work for this and idk y
  hoverInfo:
    - "<aqua>Example 1"
    - "<red>Example 2: <blue>fr"

# features currently in development. Not recommended for production
experimentalFeatures: false

commands:
  message:
    enabled: true
      # variables:
      # - <receiver-prefix> - requires Vault
      # - <receiver-suffix> - requires Vault
      # - <sender-prefix> - requires Vault
      # - <sender-suffix  - requires Vault
      # - <receiver>
      # - <sender>
      # - <message>
    sender: "<gold>You <gray>»</gray> <receiver><reset>: <message>"
    receiver: "<gold><sender> <gray>»</gray> You<reset>: <message>"

    messagesDisabled: "<red><receiver>'s messages are disabled"
  broadcast:
    enabled: true
    message: "<newline>  <dark_gray>[<bold><red>SERVER ANNOUNCEMENT</red></bold>]<white> <message><newline>"
  messagetoggle:
    enabled: true
    toggledOff: "<gray>Private Messages have been<red> Disabled"
    toggledOn: "<gray>Private Messages have been<green> Enabled"
  reply:
    enabled: true
    noReply: "<red>You don't have anyone to reply to!"
  socialspy:
    enabled: true
    # same vars as /message
    message: "<gray>[<gold>SS</gold>] » <yellow><sender></yellow> -> <yellow><receiver></yellow>:</gray> <message>"
  tp:
    tpall-enabled: true
    tphere-enabled: true
    teleported-message: "<gray>You have been Teleported by <yellow><teleporter>"
    teleporter-message: "<gray>You have Teleported <yellow><teleported></yellow> to <yellow>Yourself"
  enchant:
    enabled: true
    message: "<gray>Applied<yellow> <enchantment></yellow> to<yellow> <target></yellow> held item"
  feed:
    enabled: true
    message: "<gray>Successfully fed<yellow> <target>"
  back:
    enabled: true
    message: "<gray>You have teleported to <yellow>your <gray>previous location"
  flyspeed:
    enabled: true
  gamemode:
    enabled: true
  heal:
    enabled: true
  hunger:
    enabled: true
  invsee:
    enabled: true
  ping:
    enabled: true
  smite:
    enabled: true
  vanish:
    enabled: true
    vanishMsg: "<dark_gray>[<gold>Vanish</gold>]<yellow> <player><gray> is now in vanish."
    unvanishMsg: "<dark_gray>[<gold>Vanish</gold>]<yellow> <player><gray> is no longer in vanish."
  clearinventory:
    enabled: true
  warp:
    enabled: true
  setwarp:
    enabled: true
  deletewarp:
    enabled: true
  mutechat:
    enabled: true
    mute: "<red>Chat muted by <yellow><sender>"
    unmute: "<green>Chat unmuted by <yellow><sender>"
  sudo:
    enabled: true
    say-message: "<gray>Making<yellow> <sudoed-players><gray> say: '<yellow><input></yellow>'"
    command-message: "<gray>Making<yellow> <sudoed-players><gray> execute: '<yellow><input></yellow>'"
  report:
    enabled: false
    report-log-title: "<color:dark_gray><st>=====</color><gold><bold>Report Logs</gold><st><dark_gray>====="
    report-log-format: "<yellow><reported><gray> was reported by</gray> '<reporter>'<gray> for<yellow> '<reason>'"
    report-format: "<yellow><reported><gray> has been reported by</gray> '<reporter>'<gray> for<yellow> '<reason>'"
  uptime:
    enabled: true
    message: "<aqua><b>Uptime</b>: <gold><uptime>"
  channel:
    enabled: true
    chatChannelChange: "<yellow>Chat channel</yellow><gray> set to </gray><chat-name>"
    chatNotFound: "<red>Chat <chat-name> does not exist!"
  kit:
    enabled: true
    emptyInventory: "<red>You cannot create a kit with an empty inventory!"
    kitCreate: "<green>Created kit '<kit-name>'"
    kitNotFound: "<red>Kit with name '<kit-name>' does not exist!"
    kitAlreadyExists: "<red>A kit with the name '<kit-name>' already exists!"
    kitDelete: "<red>Deleted kit '<kit-name>'"
    kitGiveTo: "<green>Gave kit '<kit-name>' to <target>"
  clearchat:
    enabled: true
    message: "<green><name> cleared the chat"
  skin:
    enabled: true
    skinSet: "<green>Set skin to '<skin>'"
    skinNotFound: "<red>Skin not found!"
  skull:
    enabled: true
  troll:
    enabled: false