# ALL STRINGS IN THIS CONFIG USE MINI MESSAGE FORMAT
# https://docs.advntr.dev/minimessage/format.html

chat:
  enabled: false
    # variables:
    # - <prefix> - requires Vault
    # - <suffix> - requires Vault
    # - <name>
    # - <message>
  format: "<name>: <message>"

  format-urls: true
  emojis-enabled: true
  emoji-token: ":"
  emojis:
    skull: "☠"
    smile: "☺"
    frown: "☹"
    heart: "<red>❤</red>"
commands:
  message:
    enabled: true
      # variables:
      # - <receiver-prefix> - requires Vault
      # - <receiver-suffix> - requires Vault
      # - <sender-prefix> - requires Vault
      # - <sender-suffix  - requires Vault
      # - <receiver>
      # - <sender>
      # - <message>
    sender: "<gold>You <gray>»</gray> <receiver><reset>: <message>"
    receiver: "<gold><sender> <gray>»</gray> You<reset>: <message>"
  broadcast:
    enabled: true
    message: "<newline>  <dark_gray>[<bold><red>SERVER ANNOUNCEMENT</red></bold>]<white> <message><newline>"
  messagetoggle:
    enabled: true
  reply:
    enabled: true
  socialspy:
    enabled: true
    message: "<gray>[<gold>SS</gold>] » <yellow><sender></yellow> -> <yellow><receiver></yellow>:</gray> <message>"
  tp:
    tpall-enabled: true
    tphere-enabled: true
    teleported-message: "<gray>You have been Teleported by <yellow><teleporter>"
    teleporter-message: "<gray>You have Teleported <yellow><teleported></yellow> to <yellow>Yourself"
  enchant:
    enabled: true
  feed:
    enabled: true
  back:
    enabled: true
  flyspeed:
    enabled: true
  gamemode:
    enabled: true
  heal:
    enabled: true
  hunger:
    enabled: true
  invsee:
    enabled: true
  ping:
    enabled: true
  smite:
    enabled: true
  vanish:
    enabled: true
  clearinventory: # /ci
    enabled: true
  warp:
    enabled: true
  setwarp:
    enabled: true
  deletewarp:
    enabled: true
  mutechat:
    enabled: true
    mute: "<red>Chat muted by <yellow><sender>"
    unmute: "<green>Chat unmuted by <yellow><sender>"
  sudo:
    enabled: true
    say-message: "<gray>Making<yellow> <sudoed-players><gray> say: '<yellow><input></yellow>'"
    command-message: "<gray>Making<yellow> <sudoed-players><gray> execute: '<yellow><input></yellow>'"

