# ALL STRINGS IN THIS CONFIG USE MINI MESSAGE FORMAT
# https://docs.advntr.dev/minimessage/format.html

chat:
  enabled: false
  # variables:
  # - %prefix% - requires Vault
  # - %suffix% - requires Vault
  # - %name%
  # - %message%
  format: "%name%: %message%"
messages:
  broadcast: "<newline><red><bold>SERVER ANNOUNCEMENT</bold><white>: %message%<newline>"