# ALL STRINGS IN THIS CONFIG USE MINI MESSAGE FORMAT
# https://docs.advntr.dev/minimessage/format.html

chat:
  enabled: false
    # variables:
    # - <prefix> - requires Vault
    # - <suffix> - requires Vault
    # - <name>
    # - <message>
  format: "<name>: <message>"

  emojis-enabled: true
  emoji-token: ":"
  emojis:
    skull: ☠
    smile: ☺
    frown: ☹
    heart: "<red>❤</red>"
commands:
  message:
    enabled: true
      # variables:
      # - <receiver-prefix> - requires Vault
      # - <receiver-suffix> - requires Vault
      # - <sender-prefix> - requires Vault
      # - <sender-suffix  - requires Vault
      # - <receiver>
      # - <sender>
      # - <message>
    sender: "<gold>You <gray>»</gray> <receiver><reset>: <message>"
    receiver: "<gold><sender> <gray>»</gray> You<reset>: <message>"
    social-spy: "<gray>[<gold>SS</gold>] » <yellow><sender></yellow> -> <yellow><receiver></yellow>:</gray> <message>"
  broadcast:
    enabled: true
    message: "<newline>    <dark_gray>[<bold><red>SERVER ANNOUNCEMENT</bold></red>]<white> <message><newline>"
  messagetoggle:
    enabled: true
  reply:
    enabled: true
  socialspy:
    enabled: true
  tpcommands:
    tpall-enabled: true
    tphere-enabled: true
  enchant:
    enabled: true
  feed:
    enabled: true
  flyspeed:
    enabled: true
  gamemode:
    enabled: true
  heal:
    enabled: true
  hunger:
    enabled: true
  invsee:
    enabled: true
  ping:
    enabled: true
  smite:
    enabled: true
  vanish:
    enabled: true
  clearinventory: # /ci
    enabled: true
  warp:
    enabled: true
  setwarp:
    enabled: true
  deletewarp:
    enabled: true

